---
# tasks file for java_test
- name: Java Version
  shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/[^0-9._]//g'
  register: java_version

- name: Ensure Facts Directory Exists
  file:
    path: /etc/ansible/facts.d
    recurse: yes
    state: directory
  become: yes
