--- # Installing tomcat
- name: adding group tomcat
  group:
    name: '{{tomcat_group}}'
    state: present
  become: yes

- name: adding user tomcat
  user:
    name: '{{tomcat_user}}'
    group: '{{tomcat_group}}'
  become: yes

- name: downloading tomcat
  get_url:
      url: "http://archive.apache.org/dist/tomcat/tomcat-8/v{{tomcat_version}}/bin/apache-tomcat-{{tomcat_version}}.tar.gz"
      dest: /tmp/apache-tomcat-{{tomcat_version}}.tar.gz

- name: creating directory
  file:
    path: '{{tomcat_home}}'
    state: directory
    mode: 0755
    owner: '{{tomcat_user}}'
    group: '{{tomcat_group}}'
    recurse: yes
  become: yes

- name: untar tomcat
  unarchive:
    src: /tmp/apache-tomcat-{{tomcat_version}}.tar.gz
    dest: '{{tomcat_home}}'
    owner: '{{tomcat_user}}'
    group: '{{tomcat_group}}'
    remote_src: yes
  become: yes

# Because of Archive structure, all files are extracted into {{tomcat_home}}/apache-tomcat-x.x.xx
- name: Create a Link
  file: 
    src: "{{tomcat_home}}/apache-tomcat-{{tomcat_version}}"
    path: "{{tomcat_home}}/current"
    state: link
  notify:
    - save tomcat details
  become: yes

- name: Deploy Systemd File
  template:
    src: tomcat.service.j2
    dest: /usr/lib/systemd/system/tomcat.service
  notify:
    - systemd daemon reload
  become: yes

- name: Enable Tomcat Users
  template:
    src: tomcat-users.xml.j2
    dest: "{{tomcat_home}}/current/conf/tomcat-users.xml"
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
  become: yes
      
- name: Enable Tomcat Access
  template:
    src: context.xml.j2
    dest: "{{tomcat_home}}/current/webapps/manager/META-INF/context.xml"
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
  become: yes

- name: Ensure Tomcat Service Running and Enabled
  service: name=tomcat state=started enabled=yes
  become: yes
